ALTER TABLE profiles
ADD COLUMN IF NOT EXISTS onboarding_completed BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS metier TEXT,
ADD COLUMN IF NOT EXISTS secteur TEXT,
ADD COLUMN IF NOT EXISTS clients_cibles TEXT,
ADD COLUMN IF NOT EXISTS style_linkedin TEXT;
